### ISSUE TITLE
Don't intercept HTTP 301s etc.

### ISSUE THREAD

**Issue by rjw62** [est31/openinbrowser#4]
I am prompted by this add-on when trying to access http://overpass-turbo.eu/s/nnd . I think this is because it throws an HTTP 301 redirect with content-type: application/octet-stream before the redirected URL returns a normal HTML page.

This may be an error by the site owner, but nevertheless, if it is the content-type header that is tripping the add-on here, I think it would probably be better let any redirects like this through, and only consider the content-type header on the final page/document that the browser will be attempting to display/download.

**Comment by est31** [comment]
Thanks for opening an issue. The next version of the open in browser add-on will be not mine, it will live here instead: https://github.com/Rob--W/open-in-browser Please test it as well and provide any feedback for it there!

**Comment by est31** [comment]
Closing the issue as I'm archiving this repository. Please use https://github.com/Rob--W/open-in-browser instead!
