### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by avg-I** [est31/openinbrowser#5]
I think that at the moment the README should not offer to install from the mozilla addon page.
Also, the build instructions seem to be outdated.

**Comment by est31** [comment]
Thanks for opening an issue. The next version of the open in browser add-on will be not mine, it will live here instead: https://github.com/Rob--W/open-in-browser Please test it as well and provide any feedback for it there!

**Comment by avg-I** [comment]
Thank you! Moving over there.
