### ISSUE TITLE
Embedded UI

### ISSUE THREAD

**Issue by Glandos** [est31/openinbrowser#7]
Thanks for the rewrite in web-extension. It is very less integrated than before, but since I'm heavily relying on this feature, I think will get use to it.

However, would it be possible not to use a single window that replace the existing page, and use instead a popup or an iframe? It will be easier then to make a choice for "Open as", along with #6

**Comment by est31** [comment]
Thanks for opening an issue. The next version of the open in browser add-on will be not mine, it will live here instead: https://github.com/Rob--W/open-in-browser

**Comment by est31** [comment]
Closing the issue as I'm archiving this repository. Please use https://github.com/Rob--W/open-in-browser instead!
