### ISSUE TITLE
Doesn't open in browser

### ISSUE THREAD

**Issue by arantius** [est31/openinbrowser#8]
1. Navigate to https://boardgamegeek.com/filepage/33426/english-rules-kind-permission-chili-spiele
2. (Log in and) click the "Rules_Climbers02.pdf" link.
3. Get the (2.0beta5) open in browser dialog
4. Click "open in browser".
5. Get Firefox download UI

In Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

Worse, I get a file called "geekfile_download.php".  If I disable the extension and try again, I get a file with the proper name.

**Comment by est31** [comment]
Thanks for opening an issue. The next version of the open in browser add-on will be not mine, it will live here instead: https://github.com/Rob--W/open-in-browser Please test it as well and provide any feedback for it there!
